### ISSUE TITLE
No Restore bar appears on 1.4.12/b4

### ISSUE THREAD

**Issue by Saad-bloop** [Samgisaninja/SuccessionRestore#108]
on Succession 1.4.12/b4 while doing restore on any phone the after clicking erase it says restoring please wait and then there is no progress bar under it on iphone 6s it doesnot show anything and on iphone X it just shows loading sign and no bar no writting etc. I waited for hour but nothing happened 
please help

**Comment by Samgisaninja** [comment]
can you please send a log

**Comment by Saad-bloop** [comment]
How to send the log ?

**Comment by Samgisaninja** [comment]
just drop it in github comments

**Comment by Saad-bloop** [comment]
I need a bit help can you guide me how can i get the log of my succession app. Like from where can i find my log and should i get log after pressing erase and restore or before it.?!

**Comment by Samgisaninja** [comment]
go to settings
turn on logging
cause the issue
use filza or something to share /var/mobile/succession.log to this github comment thread

**Comment by Saad-bloop** [comment]
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/4254630/succession.log)
see

**Comment by Saad-bloop** [comment]
![IMG_1333](https://user-images.githubusercontent.com/61464992/75331387-6922f180-58a4-11ea-911c-a9c8c0c29a44.jpg)

**Comment by Saad-bloop** [comment]
Any idea whats the problem?

**Comment by Saad-bloop** [comment]
@Samgisaninja

**Comment by Samgisaninja** [comment]
Ok bud I'll get around to it when I get a chance. That might be a few weeks. If that's too long for you, succession is open source, and I accept contributions. I understand you're impatient, but making separate comments to spam my inbox, reacting with eye emojis to spam my inbox, and tagging me when I don't reply within an hour, again spamming my inbox... does not make me more likely to fix your problem. It's a beta release for a reason: so that I can take time to iron out these problems. Stop complaining.

**Comment by Saad-bloop** [comment]
I understand it brother. I thought it was some kind of small bug or i was doing some kind of mistake while using the app but i guess its not that. But I really appreciate you help and kindness and i am sorry for being impatient a

**Comment by Samgisaninja** [comment]
This was fixed in 853102e
