### ISSUE TITLE
iPhone 6s Plus - iOS 9.x support

### ISSUE THREAD

**Issue by DanTheMann15** [Samgisaninja/SuccessionRestore#135]
after spending two hours and feeling like i've been tortured;<br>i have posted keys for the release versions of [iOS 9 for the iPhone 6s Plus](https://www.theiphonewiki.com/wiki/Firmware/iPhone/9.x#iPhone_6s_Plus).

and because i am one of those "lucky" souls to have a device with s8000 and one with s8003<br>i did both N66AP and N66mAP

9.x beta keys are also coming soon for this device, but only for 9.3-b1 through 9.3.3-b4.

**Comment by Samgisaninja** [comment]
Hi. I appreciate you getting those keys, and I’m sure the community will appreciate you getting those keys, however unfortunately that’s not the reason why Succession doesn’t work on the 6S iOS 9.X.

Apple does not allow activation of iPhone 6S and 6S Plus on iOS 9. The *only* way to get the phone to work after a restore to iOS 9–succession or otherwise—is hacktivation. This has moral and legal implications that I want no part of, so I cannot in good faith allow Succession to work on the 6s on 9.X. If you modify succession’s source code to remove the “is this an iPhone 6s on iOS 9” check and use that modified build for personal use, I can do nothing about that. But that will never be shipped in any official builds.

**Comment by DanTheMann15** [comment]
i find that odd that apple doesn't allow activation of iOS 9 on the iPhone 6s/6s Plus, while they allow activation on iPhone SE running iOS 9, how i know is because i actually still have an iPhone SE that runs iOS 9.3.3, it's carrier unlocked as well and activates just fine without a SIM card.

i don't see why apple would not allow activation on those devices on iOS 9, with the exception on whether it's iCloud or SIM locked.

when i opened this, i already knew that it didn't require an update to succession itself, it's just the Readme.md file.
