### ISSUE TITLE
Working, please do not leave the app...

### ISSUE THREAD

**Issue by JarrettCS** [Samgisaninja/SuccessionRestore#45]
Similar to an issue that was resolved. The ipsw was deleted but at the link found the ipsw is still there just not downloading. This is on iPhone XS Max. On my iPad Pro, also A12 it works fine.

![IMG_0015](https://user-images.githubusercontent.com/8755377/61422202-48d39300-a8d0-11e9-841d-f5f6f4855379.png)

**Comment by Samgisaninja** [comment]
change networks and retry

**Comment by JarrettCS** [comment]
Have tried on over three different WiFi connections and cellular. Also have restored fs and also erased all settings.

Also, if I manually download the file from that link and place it in the directory it says extracting but never actually starts.
Thanks for looking into it!

**Comment by dillydylann** [comment]
You can try downloading the IPSW file [here](http://updates-http.cdn-apple.com/2018FallSeed/fullrestores/041-24857/D0D25388-E786-11E8-B39F-0A9D55D8F596/iPhone11,6_12.1.1_16C5050a_Restore.ipsw) and copy it to "/var/mobile/Media/Succession" and then rename it to "ipsw.ipsw"

**Comment by JarrettCS** [comment]
It gets stuck on unzipping if I manually insert an ipsw.

**Comment by JarrettCS** [comment]
Issue still persists.

**Comment by Samgisaninja** [comment]
Succession 1.3.5 should fix this, if you're still having this issue, can you try that?

**Comment by JarrettCS** [comment]
> Succession 1.3.5 should fix this, if you're still having this issue, can you try that?

Sadly, it still didn't fix it. Also restored root-fs and reset all settings before rejailbreaking then attempting to run 1.3.5. :(

**Comment by Samgisaninja** [comment]
so this is actually fairly obvious now, you are/were running a beta iOS, and as you can clearly see in the second to last line of the URL... there's literally a space " " in the middle. Everything after the space shouldve been truncated.

This was fixed by 424fc6c. Since this was a server-side issue, all versions of succession 1.3+ will automatically find the correct link, and I don't need to release an update to fix that.
