### ISSUE TITLE
Version 1.4.4 doesn’t delete rootfs 

### ISSUE THREAD

**Issue by jonayh** [Samgisaninja/SuccessionRestore#76]
As the title says, the full restore finally works but when you go to rejailbreak it doesn’t have to create a rootfs

**Comment by Samgisaninja** [comment]
that's intentional. succession doesn't touch APFS snapshots.

EDIT: And also, you shouldn't either. The system snapshot is present on all devices (even devices that have never been jailbroken before) 11.3+, and deleting it will break unc0ver/chimera's "restore rootfs" and checkra1n's "restore system" features.
