### ISSUE TITLE
Restoring on iPhone 5c iOS 8.4 - Succession requests a package "attach" from pmbonneau repo, but host is down

### ISSUE THREAD

**Issue by dingoosh** [Samgisaninja/SuccessionRestore#78]
Succession requires a package called "attach" available from the repo http://pmbonneau.com/cydia. I can't fetch this package because the repo is dead. Does anyone have a .deb they could share?

**Comment by Samgisaninja** [comment]
reposting the deb on GitHub would be a license violation, so please don't do that. 

The repo is down, but they appear to still be hosting the deb at http://pmbonneau.com/cydia/com.pmbonneau.attach_1.0_iphoneos-arm.deb

**Comment by dingoosh** [comment]
His /cydia/ server is down entirely - there doesn't appear to be any way to access any .debs hosted there. Does the link you just shared work for you? It's completely dead for me.

**Comment by Samgisaninja** [comment]
oh, huh, that link worked yesterday, now it doesn't.

# F

**Comment by dingoosh** [comment]
I'll keep watch on that page in case it comes back up. Thanks anyway!! (and thanks for your work in general!)

**Comment by Samgisaninja** [comment]
I'd like to leave this open as long as it's still a problem

**Comment by dingoosh** [comment]
I see you implemented a fix. I just spent a few hours trying to compile to no avail, so when you get a chance would you mind compiling and uploading the .deb under a new release? Thanks again!

**Comment by Samgisaninja** [comment]
Unfortunately the fix was broken and I've gone back to using attach. Fortunately, after the pmbonneau repo went down, I contacted comex, and he has given me express permission to use it, so I don't have to depend on pmbonneau for hosting as I can just bundle it. 

I use discord to conduct prerelease testing. I already have someone in the group that is helping me fix this, but if you'd like to join use invite code "jb" and ping me, Samg_is_a_Ninja#6113
