### ISSUE TITLE
stuck Attaching... 6S 12.4

### ISSUE THREAD

**Issue by noelesther** [Samgisaninja/SuccessionRestore#84]
Hello. 

I want to restore my 6S 12.4

When I download ipsw then enter Prepare for restore!, Stuck Attaching over 8hours.

plz help me. thanks.

log is just this

[SUCCESSIONLOG 1.4.6: 2020-01-16 01:12:48 +0000] Line 91: Mountpoint exists, continuing
[SUCCESSIONLOG 1.4.6: 2020-01-16 01:12:48 +0000] Line 164: attachDiskImage called!
[SUCCESSIONLOG 1.4.6: 2020-01-16 01:12:48 +0000] Line 167: using hdik to attach disk image
[SUCCESSIONLOG 1.4.6: 2020-01-16 01:12:48 +0000] Line 172: hdik /private/var/mobile/Media/Succession/rfs.dmg
[SUCCESSIONLOG 1.4.6: 2020-01-16 01:12:48 +0000] Line 179: hdik completed with

[SUCCESSIONLOG 1.4.6: 2020-01-16 01:12:48 +0000] Line 206: changedDevContents:

**Comment by noelesther** [comment]
I restored with 1.3.6

**Comment by Samgisaninja** [comment]
I can't recommend that as there are several issues with 1.3.6 that have since been fixed, but glad it worked for you nonetheless

**Comment by Samgisaninja** [comment]
IDK if this is fixed or not so I'm gonna leave it open for now

**Comment by tay200k** [comment]
Had this issue with my ipod 6th gen (checkra1n), as above I downgraded but like 3 versions and it worked.

**Comment by Greigh** [comment]
This is not fixed @Samgisaninja. I get the error on my XS Max 12.4.

**Comment by Samgisaninja** [comment]
Can you send a log from 1.4.10

**Comment by angelstoned** [comment]
Hey, I just upgraded to the latest version and after extraction to downgrade. I’m stock on this for a long time without any response! Please help
![image](https://user-images.githubusercontent.com/58833833/73334841-c7c06580-423b-11ea-8e0a-f488f0b45cfe.jpg)

**Comment by angelstoned** [comment]
I’m on iPhone 8 Plus and this is my log
![image](https://user-images.githubusercontent.com/58833833/73334961-14a43c00-423c-11ea-8445-37843f337f87.jpg)

**Comment by angelstoned** [comment]
Am I missing anything

**Comment by Samgisaninja** [comment]
Can yall please add samgisaninja.github.io/beta

Install succession 1.4.12-b1

Enable logging and cause the issue again

Send me /var/mobile/succession.log

**Comment by angelstoned** [comment]
Thank you @Samgisaninja for explaining.

I will add it now and give it another try! Thank you will keep you posted

**Comment by angelstoned** [comment]
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/4131472/succession.log)
 

Here you go. Problem still there! 
Would it be possible to try out previous versions, and the downgrade would work? 
I already tried so far about 7 different ones and I haven’t had any luck so far!

**Comment by Samgisaninja** [comment]
sometimes downgrading helps for some people, sometimes not.

your log is by far the most useful log I've ever received, specifically the `[SUCCESSIONLOG 1.4.12~b1: 2020-01-29 23:12:59 +0000] Line 209: I am: 501` bit

I have yet to confirm this, but I now believe there is a single underlying problem with succession that's causing this issue and also #44... I'll need to talk to some other developers about it though.

**Comment by angelstoned** [comment]
I am very glad to hear the log will be useful. You’re the man! I am pretty confident that you will eventually figure it out and fix it. 
I tried so many previous versions, but none seems to work. But it’s okay I’ll just wait for the next fix.

In the mean time I’ll keep messing around and hopefully learn new things. I find this very interesting and I would love to learn all the basics, including codings etc.. 

I’ll be looking forward to your next answer. And if you need any logs, I’ll be more than happy to run them. 

And thanks a lot for the amazing work you do! It is truly inspiring! Thank you

**Comment by Samgisaninja** [comment]
Yeah, sbingner had some good advice, this will probably be a weekend project though. 

> In the mean time I’ll keep messing around and hopefully learn new things. I find this very interesting and I would love to learn all the basics, including codings etc

I would find a course online to learn the *very* basics of classes and messages, then just dive in. When I first started succession nearly 3 years ago, I knew what classes were and how to send messages (sending messages is also referred to as "calling a method"--but you'll learn that soon enough). Creating succession was how I learned to code. Once you have the basics, start working on a project. If you don't know how to do something, google it, usually someone else has already asked what you're asking, and there's plenty of great answers online. On the off chance there isn't, \#development on the r/jailbreak discord and /r/jailbreakdevelopers have tons of very knowledgable people answering questions from new developers (its a really great community, I would never have been able to get this far without them). 

Plus, being able to code is a really really useful skill nowadays and it's only becoming more important each year. I just started my freshman year of college as a meteorology (atmospheric science/weather) major. It's really amazing the amount of doors that have opened for me this year just because I'm able to say "I know how to code". I'm now learning python and c++ for completely non-jailbreak related projects, which is much easier to do since I already have a basic grasp on how object-oriented languages work. 

I wish you good luck in your learning experience, feel free to ask me any questions you have and I'll do my best to help (or refer you to someone who can)

**Comment by Samgisaninja** [comment]
(sorry that got off topic)

**Comment by anubismxx** [comment]
I have the same problem 
![E3FDCC64-0B5D-4E32-AC6F-20568FD3190D](https://user-images.githubusercontent.com/20994203/73462794-f3c60e80-4341-11ea-9cb1-f200d48e4154.jpeg)

[SUCCESSIONLOG 1.4.12~b1: 2020-01-30 14:53:23 +0000] Line 92: Mountpoint exists, continuing
[SUCCESSIONLOG 1.4.12~b1: 2020-01-30 14:53:23 +0000] Line 167: attachDiskImage called!
[SUCCESSIONLOG 1.4.12~b1: 2020-01-30 14:53:23 +0000] Line 170: using hdik to attach disk image
[SUCCESSIONLOG 1.4.12~b1: 2020-01-30 14:53:23 +0000] Line 175: hdik /private/var/mobile/Media/Succession/rfs.dmg
[SUCCESSIONLOG 1.4.12~b1: 2020-01-30 14:53:23 +0000] Line 183: hdik completed with
hdik: must be run by root

[SUCCESSIONLOG 1.4.12~b1: 2020-01-30 14:53:23 +0000] Line 209: I am: 501
[SUCCESSIONLOG 1.4.12~b1: 2020-01-30 14:53:23 +0000] Line 217: changedDevContents:

**Comment by dylanchapell** [comment]
I was having this same issue on iPhone 8 13.3. Same hdik must be run by root in the log. I installed the test version from the beta repo, 1.4.12-b1, and it fixed my issue. Phone just finished restoring. Thanks for such a great project! I have included my log from before updating just in case it is useful.
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/4136534/succession.log)

**Comment by cdlenfert** [comment]
Had the same issue on an iPhone 6 with 12.4. Using 1.4.12-b1 worked for me. Thank you!

**Comment by angelstoned** [comment]
Thanks a lot for the amazing tips @Samgisaninja I will definitely keep it in mind. And I joined both forums right now  the r/jailbreak and /r/jailbreakdevelopers on reddit. Since I don’t have a Mac yet, I believe I’ll start with python or c++ just like you :) and hopefully some doors will open up for me too in the future. But first thing first I will learn the basics of github and how it works. Because I don’t even know how to you DM here lol, since we’re off topic! 

I see some people 12.4.12b fixed the issue for them. I will run it again today.

**Comment by Samgisaninja** [comment]
This issue has been moved into #89
