### ISSUE TITLE
Succession doesn't always launch as root

### ISSUE THREAD

**Issue by Samgisaninja** [Samgisaninja/SuccessionRestore#89]
This leads to all child processes being spawned as mobile. Attaching, mounting, and rsync all require root. This is the root cause of #44 and #84 

Possible resolutions of this issue are to:
1. Make sure succession is actually running as root. (I'm not sure what else I can do at this point)
2. Make succession run as mobile, and get root temporarily (I'll probably end up doing this)

(2) can be accomplished securely using a number of different ways:
* I could add Cydia's cydo as a wrapper for succession to get root (succession is already GPL so there no issue there)
* I could add Zebra's [supersling](https://github.com/wstyres/Zebra/blob/master/Supersling) as a wrapper (same thing there with GPL
* I could use SnapBack's solution for this, creaturesurvive's [iAmGRoot](https://github.com/CreatureSurvive/iAmGRoot)

Currently I'm thinking of using Zebra's because it's pure C (which is easier for me to read, although I do need to learn C++ at some point soon for a different project) and I don't have to work around coolstar intentionally breaking it (which he did with cydo).

**Comment by cdlenfert** [comment]
Interesting. I don't know if this is relevant, but I was unable to launch Cydia after the first time 1.4.11 failed to restore my device. (iphone 6 on 12.4). I also couldn't reinstall Cydia via Checkra1n. I eventually had to use local SSH on my phone to delete /var/mobile/Library/Cydia/Metadata.cb0. At that point I was able to install the 1.4.12 beta of Succession and everything went smoothly.

**Comment by angelstoned** [comment]
Hi @Samgisaninja I intentionally ran 1.4.11  first then upgraded to 1.4.12-b. To see if it fixes it and I registered this log 
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/4136899/succession.log)

I am still using the same device iPhone 8+ Model A1897.

**Comment by angelstoned** [comment]
I just noticed the resolutions, I will try them now! Finger crossed 🤞🏻

**Comment by angelstoned** [comment]
Can you please guide me into file Path of succession in which I need to run as root? 
And I am going to upload to you my phones restore logs. I’m not sure if it can help you with anything but just incase it does.

[restore 2.log](https://github.com/Samgisaninja/SuccessionRestore/files/4137106/restore.2.log)

[restore.log](https://github.com/Samgisaninja/SuccessionRestore/files/4137107/restore.log)

**Comment by Samgisaninja** [comment]
To reduce the number of emails this thread sends, I'll be replying to y'all in one long/rambling comment:

@cdlenfert thats not related, Cydia runs as mobile (which is why it has cydo)

@angelstoned the issues were "closed" but not "resolved". I closed them to merge them into one issue. 

I believe that launching succession as root (kill from app switcher, then `/Applications/SuccessionRestore.app/SuccessionRestore` in a root shell) will fix the problem temporarily, but that's not a solve.

**Comment by pissawi** [comment]
stuck on attaching...
can't restore to 12.4.2
iPhone 6s ios 13.3
any solution please

**Comment by IMS212** [comment]
Version of succession?

**Comment by pissawi** [comment]
succession 1.4.12-b1

**Comment by IMS212** [comment]
WAIT WAIT are you trying to go to 12.4 from 13? That’s not gonna work. The only versions you can downgrade to is 13.2.3

**Comment by pissawi** [comment]
also with 13.2.3 , stil stuck on attaching "this should take less than 10 seconds" :( 
i try both of them 13.2.3 and 12.4.2

**Comment by IMS212** [comment]
1: don’t ever try to go to 12.4, it will bootloop you.
2: open a terminal as root (you can search how), close succession from the app switcher, run `/Applications/SuccessionRestore.app/SuccessionRestore` as root then open succession again and try. Does that work?

**Comment by pissawi** [comment]
i will try and i told you , but i don't know how to run terminal as root, any video please ?

**Comment by IMS212** [comment]
Ok, download terminus from the App Store and open it. Create a new host with these options
Hostname: `localhost`
Port: 44
Username: `root`
Password: `alpine`
That should get you into a root shell to run that command.

**Comment by pissawi** [comment]
Abort trap: 6 when i run that directly from device using newterm

**Comment by pissawi** [comment]
![2](https://user-images.githubusercontent.com/60550639/73596736-3f84dd80-4525-11ea-9154-264fd491b0fb.jpg)

**Comment by IMS212** [comment]
I’m going to test quickly on my device, going to see the result

**Comment by pissawi** [comment]
okey thanks

**Comment by IMS212** [comment]
It works for me, 13.3.1 iPhone 8, 1.4.12b1

**Comment by IMS212** [comment]
AHA I found it, you missed one of my instructions. You were supposed to close succession from the app switcher first

**Comment by pissawi** [comment]
can you show me the steps please

**Comment by IMS212** [comment]
Just close succession as from the app switcher menu, then try the command again. If the terminal stays frozen on the command, you’re good to open succession and try again.

**Comment by pissawi** [comment]
okey i will try and told you Thank you <3

**Comment by pissawi** [comment]
always the same thing stuck on attaching , i run the command and it frozen as you said but when i open succession again i still stuck on attaching :(

**Comment by pissawi** [comment]
![20200201_192150](https://user-images.githubusercontent.com/60550639/73597057-83c5ad00-4528-11ea-9694-b1bcdc45c262.jpg)
![2](https://user-images.githubusercontent.com/60550639/73597058-83c5ad00-4528-11ea-86b9-ad9fa2e33f2d.jpg)

**Comment by Samgisaninja** [comment]
@pissawi when it failed even after launching via terminal, was that 1.4.12-b1, and did you get a log from that

**Comment by pissawi** [comment]
@Samgisaninja yes sure i was using 1.4.12-b1 , yes i have log files i will upload it give me 5min

**Comment by pissawi** [comment]
I try that on two diffent devices and have the same issue , stuck on attaching

**Comment by AhseesMalik** [comment]
i stuck on attaching ca you please solve this issue

**Comment by Samgisaninja** [comment]
^banned for spam/begging

**Comment by angelstoned** [comment]
Hey @Samgisaninja hope you’re having a good weekend so far!
I just got the chance to try last resolution you suggested and here is my log 
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/4143325/succession.log)

**Comment by pissawi** [comment]
Hey @Samgisaninja that's was happened on my device
![IMG_0024](https://user-images.githubusercontent.com/60550639/73600273-09a81f00-454e-11ea-9dc7-f4612ee5d2f6.PNG)
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/4143327/succession.log)

**Comment by Samgisaninja** [comment]
Hmm, I suppose the "launch it from terminal" workaround doesn't work as reliably as I'd hoped. I'm still looking into a proper fix, but that could be a few weeks.

**Comment by angelstoned** [comment]
Good news @Samgisaninja  after long research I was finally able to fix it. I guess all this time I spent on it trying to fix it was worth it. And it’s a good feeling to be honest. That’s the reason why I’m very interested in learning how to code.. and I think I might have found a solution for you too. But only you who could tell, since I still don’t know how to code, but I’ll be happy to show you what I found. And by the way, your assumption to launch it from terminal is correct. 
And the fix is pretty easy, all I needed to do is: chown root:wheel ./Applications/SuccessionRestore.app/SuccessionRestore
Chmod 6755 ./Applications/SuccessionRestore.app/SuccessionRestore

And then 
I made sure to kill it with app switcher
I personally just ran the command killall SuccessionResore
And ran

./Applications/SuccessionRestore.app/SuccessionRestore

Opened Succession and it worked like a charm :) thanks a lot for making this amazing app! 

10 seconds wait.. fixed 

![9405D2B9-5BA0-4689-9F0C-05F1471A239B](https://user-images.githubusercontent.com/58833833/73615840-e32fc580-45d9-11ea-9e4d-4066301a1393.png)
![AB43F483-D4FB-4D6B-BCBC-A1AD4B56CDA8](https://user-images.githubusercontent.com/58833833/73615841-e32fc580-45d9-11ea-99e1-24a3ee18e515.png)
![899747BB-159F-46F7-8A56-8E8244AD5063](https://user-images.githubusercontent.com/58833833/73615842-e32fc580-45d9-11ea-9edd-e877441678a6.png)
![844F07C2-9084-4AA0-A99A-A3CB8DF0C4B0](https://user-images.githubusercontent.com/58833833/73615843-e32fc580-45d9-11ea-8a48-5aa4704e07af.png)



And this is for you @Samgisaninja 
I found this in Ivano’s blog under iOS - Run application with root privileges

Explicitly call "setuid(0)" and "setgid(0)" very early in your code (specifically in "main", somewhere before calling "UIApplicationMain"). Here's a quick example:



#import <UIKit/UIKit.h>
#import "MyAppDelegate.h"
 int main(int argc, char *argv[]){
    @autoreleasepool
     {
        // Set uid and gid
       if (!(setuid(0) == 0 && setgid(0) == 0))
       {
            NSLog(@"Failed to gain root privileges, aborting...");
             exit(EXIT_FAILURE);
         }
 
         // Launch app
     return UIApplicationMain(argc, argv, nil, NSStringFromClass([MyAppDelegate class]));
     }
 }


Well that was easy, wasn't it? But what about that "don't run directly" madness?

Essentially, you need to add a "launch script" to the app bundle, which will be called when you tap on the SpringBoard icon, and will actually launch the app.

1. Not doing this will result in your app being terminated as soon as it attempts to setuid.

Assuming the executable of your app is named "myApp", all you have to do is rename it to "myApp_", and add a script called "myApp" to the .app bundle. The script should be structured like this:

#!/bin/bash
myAppPath=$(dirname "$0")
exec "$myAppPath"/myApp_ "$@"

Finally, make sure to set the ownership of the script to "root:wheel" and its permissions to "755".

**Comment by Samgisaninja** [comment]
> chown root:wheel ./Applications/SuccessionRestore.app/SuccessionRestore
> chmod 6755 ./Applications/SuccessionRestore.app/SuccessionRestore

1. You should actually not have the . in front of the leading / on those as that might return "no such file or directory", using the absolute path is better practice, but that's beside the point
2. Succession comes that way. See [the compile script](https://github.com/Samgisaninja/SuccessionRestore/blob/master/compile) (which, yes, I know "sudo fakeroot" is redundant, but I keep forgetting to remove that and it doesn't really make a difference

Back in summer 2017 when I started this project, I read that blog post. The issue with Ivano's blog is that, it doesn't work on some old versions of meridian, or electra/chimera. It is mostly implemented, with some modifications to make it work on those jailbreaks: [main.m](https://github.com/Samgisaninja/SuccessionRestore/blob/master/SuccessionRestore/main.m)

However, as I've learned, since succession actually doesn't need root for downloading/extracting, it is better practice to have it run as mobile, and then *ask* another process to do things as root. That "another process" will be `succDatRoot`, an adapted version of Zebra's supersling.

**Comment by angelstoned** [comment]
Very interesting! Again thanks a lot @Samgisaninja for everything. I just want to ask you for a way to contact in the future, is your public email good to reach out to you? Because without a single doubt I am going to have bunch questions in the future. I would like to email you from my personal email, in regards of learning, online classes, materials I need, etc... I need your advice on where to start, and it would be great if you can refer me to the right direction. So I wouldn’t waste too much time on unnecessary lessons.

**Comment by pissawi** [comment]
the solution it work for me too but it still stuck on apple logo i should boot it with chekra1n every time i reboot the device thanks @Samgisaninja thanks @angelstoned

**Comment by Samgisaninja** [comment]
@angelstoned my @unc0ver.dev email will work, fastest reply will probably via discord on https://discord.gg/jb

**Comment by Samgisaninja** [comment]
@pissawi succession is not intended for downgrading and any issues you run into after attempting to downgrade should not be reported.

**Comment by pissawi** [comment]
Aaah ok bro sorry --' thank you so much

**Comment by cffj** [comment]
I follow with you.success fix Attching but finally bootloop

**Comment by jack980517** [comment]
I'm trying to restore on iOS 10.3.3 (jailbroken with Meridian) and it doesn't work. After I manually created the folders and emptied /var/MobileSoftwareUpdate, it got stuck at "Attaching". I guess it's the same problem here, since it looks like a permission problem, and Meridian is mentioned here.

**Comment by Samgisaninja** [comment]
Yeah--I've started option 2, which will hopefully be a 4-part process:

- [x] Rip supersling from zebra and add to compile script so that it's bundled in SuccessionRestore.app
- [x] add succDatRoot calls to RestoreViewController's implementation
- [x] test and patch
- [x] release

Unfortunately I made the mistake of taking 18 credit-hours this semester, this could be a while

**Comment by tomsmile0** [comment]
I still find the solution for me right now.  Thank you for helping me.
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/4211501/succession.log)

**Comment by Samgisaninja** [comment]
Implemented in 1.4.12

**Comment by Leeksov** [comment]
My program also hangs on "This should take less than 10 seconds" here are my file
[succession.log](https://github.com/Samgisaninja/SuccessionRestore/files/5939376/succession.log)
